import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

export default function Home({ newResults }) {
  return (
    <div >
      <Head>
        <title>twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen mx-auto max-w-7xl'>
        {/* {Sidebar} */}
        <Sidebar />
        {/* {Feed} */}
        <Feed />
        {/* {Widgets} */}
        <Widgets newResults={newResults.articles} />
        {/* {Modal} */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch(`https://saurav.tech/NewsAPI/top-headlines/category/business/us.json`)
  const newResults = await res.json()

  return {
    props: {
      newResults
    }
  }
}